### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by jhta** [jurassix/react-validation-mixin#15]
I have this problem:
Error: Cannot find module 'lodash.isObject' from '/var/source-projects/neo/node_modules/react-validation-mixin'
 You need change the ValidationMixin.js file in the line
![screenshot from 2015-04-07 13 17 34](https://cloud.githubusercontent.com/assets/5351504/7030388/d7398c8e-dd29-11e4-95f5-71d0491fcf98.png)
![screenshot from 2015-04-07 13 19 52](https://cloud.githubusercontent.com/assets/5351504/7030389/d938a934-dd29-11e4-9608-dc3d997b2ddc.png)

 5 "isobject" by "isObject"

**Comment by jurassix** [comment]
Thanks for the report. Taking a look...

**Comment by jurassix** [comment]
Which version do you have have installed? Can you upgrade to version 4.0.3 and see if the issue still extists?

From the `package.json` I am requiring in these lodash modules with the same lowercase convention:
```javascript
  "dependencies": {
    "lodash.flatten": "^3.0.0",
    "lodash.isempty": "^3.0.0",
    "lodash.isobject": "^3.0.0",
    "lodash.result": "^3.0.0",
    "lodash.union": "^3.0.0",
    "object.assign": "^1.1.1"
  }
```

**Comment by jurassix** [comment]
[You can see the lodash.isobject documentation here]
(https://www.npmjs.com/package/lodash.isobject)

**Comment by jurassix** [comment]
Closing this issue. Please reopen if you are still having an issue.
