### ISSUE TITLE
Result too big size when using with react

### ISSUE THREAD

**Issue by nguyenxuantuong** [jurassix/react-validation-mixin#20]
Hi,

I am wondering is there anyway to reduce the size of the library. When I use with react, it increases more than 2Mb of the output file (unminified), which is a lot and slow down my webpage.

Thank.

**Comment by jurassix** [comment]
This library is pretty small, but the dependencies are not. Both Joi and React are quite substantial projects. I am working towards giving an option for other validation libraries like Revalidator. see issue #14
