### ISSUE TITLE
Issue with the fields

### ISSUE THREAD

**Issue by gilperon** [jurassix/react-validation-mixin#22]
Hi,

First of all I would like to say thank you for your jurassix library, it's amazing. :) I just have an issue that is probably a bug on it. Please, open your own demo at this link:

http://jurassix.github.io/react-validation-mixin/

After that open your browser console (F12) and paste the following code:

document.getElementById("email").value = "testing@gmail.com";

It will work fine, I mean, the "Email" field will receive the value "testing@gmail.com". But there is a problem: when I try to send the form, clicking the SIGN UP button at the bottom of it the error message says that the Email field was not filled right. Can you tell me how to solve this bug cause I really love your library and I use it in dozens of websites I develop. It's pretty handy and really nice!

Hope you can help me.

OBS: I know my question can be solved with a different approach but I need to give my customer to ability to manipulate the form fields with JS at the console cause they have testing tools to make sure the sign up form is working and one of my customer pointed me this "bug" yesterday.

**Comment by jurassix** [comment]
I'll take a look and see what options we have for supporting this within React.

**Comment by jurassix** [comment]
The real issue is that when manually setting the value of a React controlled input you are not firing any events to let React know the value has changed; no 'change' event triggered. _I'm assuming you cannot have the client manually fire change after updating the the value?_ 

Example:  _since all my event listeners are on `blur` this will signal to React to kick in._

```javascript
  var email = document.getElementById("email");
  email.value = "testing@gmail.com";
  email.dispatchEvent(new Event('blur'))
````

If you cannot have the client add the `dispatchEvent` logic, you can still address this by overriding the `getValidatorData` function. Basically the idea is that since you have input that is entered outside of React you cannot validate your state directly, you need to use another api to ensure the DOM value is used: `React.findDOMNode(this.refs.email).value`. This may cause issues with your components functionality that relies on `state` but the validation will work.

```javascript
getValidatorData: function() {
  return {
    email: React.findDOMNode(this.refs.email).value
  };
}
```

**Comment by gilperon** [comment]
Hi, thank you so much for helping me into this. You are very kind.

About this issue, you are right, indeed, changing the value of the input is not making React fire the change event. I can ask my customers to execute any JS code you gave me, they dont care. It can be a big or small JS. I just need someway to change the value of the input and have your excelent library to recognize this new value.

I tried your code below and it didnt work, it changed the value of the input but when I clicked the SIGN UP button I still got an error on email field.

  var email = document.getElementById("email");
  email.value = "testing@gmail.com";
  email.dispatchEvent(new Event('blur'))

Your another suggestion of overriding "getValidatorData" I think I didnt get it. I am not too smart into React and into your library as I would like, because of that I didnt understand your last suggestion. Should I try to copy/paste your code into the browser console? I need a solution that can be copied/pasted in the console.

If you know how to dispatch the "onchange" event of the input maybe this "bug" would be solved. But I already tried dispatching this event with many different JS codes and none of them work.

I love your library and this is the first time I really find a small problem. I am tired of using many other libraries in the past and yours is far way the best but unfortunatelly I have this "bug" that I need to find a solution cause my customers demand a way to set the value of the input with JS.

Hope you can find a solution to this, I will be following this thread daily and will be glad for any, any, any help you can give me to solve this "bug".

**Comment by jurassix** [comment]
This seems promising: http://newscentral.exsees.com/item/787e02a0a25b5875220484d732721d75-2457dcfdbc2a9434c10753adb688d5df 

Basically, you will need to jump through some hoops to get React to respond to manually updated input. I think the above link should work as long as you expose `React` on the page. _I also think this is would be the recommended way to do what your trying to do._

To further expand on `getValidatorData` api. This api is exposed as a way to provide data to this library on `validate`. By default this library uses `this.state` as data, but if you data comes from props you would do the following:

```javascript
getValidatorData: function() {
  return this.props;
}
```

With the above whenever `this.validate` is called `getValidatorData` will also be called to get the data to validate. In your case you have __uncontrolled__ input data, because it was entered outside of React and is not stored inside `state` or `props`. For uncontrolled data you need to get the data out of the DOM and return it from `getValidatorData`:

```javascript
getValidatorData: function() {
  return {
    email: React.findDOMNode(this.refs.email).value
  };
}
```

Above we assume we have a single field, email, and we grab the DOM value. This is contrived, but it should be enough for you to get going. 

The real issue with this approach is you are outside of react and limits what you can do. I would recommend using the `React.addons.TestUtils.Simulate.change` from the link to solve your issue. 

If you put together a jsbin or other working example I'll help you get to the solution you are looking for.

**Comment by gilperon** [comment]
@jurassix nice explanation! Really nice. Unfortunatelly it would be too hard to me open every website I created and make this change only to allow my customer to interact with the form. Your getValidatorData approach is really good and it will certainly work pretty well! But I am more interested in exposing the onchange handler. I have no idea how to do that, do you know how do I expose the onchange event so I can call it later in the browser console?

**Comment by jurassix** [comment]
To expose your onChange handler you would need to update every site too! Since your handlers are encapsulated inside the React component you would need to `componentDidMount` expose the handler to the the window or other console accessible object; and on `componentWillUnmount` clean up the exposed handler. Again this is a manual change. 

You might also try to simulate the events: http://facebook.github.io/react/docs/test-utils.html

**Comment by gilperon** [comment]
:( Ok, at least it's a solution. I will implement it on every website.

I thank you so much for helping me into this, I will use your manual solution :) I am very glad you helped me, keep up the good work!

**Comment by jurassix** [comment]
Do a quick test and see if you can use the simulate tools too, it might work, and shouldn't require any code changes:

```javascript
var node = React.findDOMNode(this.refs.email);
React.addons.TestUtils.Simulate.change(node, {target: {value: 'testing@gmail.com'}});
```

**Comment by gilperon** [comment]
Your idea of simulating the event is muuuch better indeed! But I didnt get it to work. I opened http://jurassix.github.io/react-validation-mixin/ and after the page load I executed the last code you provided me (2 lines of code) in the console but it gives me the following error:

ReferenceError: React is not defined

Why React is not defined if you example page loads React?

**Comment by jurassix** [comment]
You won't be able to test on my example page. I would need to expose React to the window. I'll update the example when I have some time and ping back. You can try to test on one of your client pages if possible.

**Comment by gilperon** [comment]
Again I say thank you thank you thank you! I will try it on a page of my customer but I think React is not exposed too and I have no idea how to expose it... anyway, if someday you expose it on your page I would be glad if you could tell me so I can open your page and test it there! 

Thank you, many thanks!

**Comment by jurassix** [comment]
Ok I have exposed React on my examples page and tested that this is a working solution! 

```javascript
var email = document.querySelector('#email');
React.addons.TestUtils.Simulate.change(email, {target: {value: 'testing@gmail.com'}});
```

To expose React you need to find the entry point of your app and set `window.React = React;` or don't bundle React into your app and add it as an external dep.

You are good to go.

**Comment by gilperon** [comment]
A M A Z I N G! It worked PERCETLY! You are really smart and a really good person, you helped me a lot! 

If I am not abusing your patience, I just would like a final help if possible. You agree with me that if I try to expose the React I will have to change the code of all the websites I created using your library, right? Cause as you said, I will have to change a little the code of the entry point of React in each one of my websites, right?

So your last suggestion I think is much better. I think that excluding React with a JS code and importing it again is much easier cause I dont need to change anyone of my websites that use React, right?

So my question would be this: how to I destroy the React object and import it again? I know I can import it with the code below but I think you are much more smart than I to suggest the right way:

    var new_react_script = document.createElement("script");
    new_react_script = "//fb.me/react-0.13.3.js";
    document.documentElement.insertBefore(new_react_script,null);

So how can I destroy the React object and import it again? Do I really need to destroy the React object if it was not exposed (that's my case, it was not exposed)?

**Comment by jurassix** [comment]
If you are including React via a script appended to the body then React should already be added to the window. You will need to change the to using https://fb.me/react-with-addons-0.13.0.js

**Comment by gilperon** [comment]
Hello Jurassix!

I changed my code to the one bellow but it still does not work, I mean, if I copy/paste the code below to the console I still cant use the React object.

    var new_react_script = document.createElement("script");
    new_react_script.src = "https://fb.me/react-with-addons-0.13.3.js";
    document.documentElement.insertBefore(new_react_script,null);

**Comment by jurassix** [comment]
try:
```javascript
var new_react_script = document.createElement("script");
new_react_script.src = "https://fb.me/react-with-addons-0.13.3.js";
document.body.appendChild(new_react_script);
```

**Comment by jurassix** [comment]
Ok I can get both your and my code to add React to the console? Maybe you having another issue?

**Comment by gilperon** [comment]
Yes, what I would like is to be able to copy/paste a code to my console and have the email field filled. Something like this:

        var new_react_script = document.createElement("script");
        new_react_script.src = "https://fb.me/react-with-addons-0.13.3.js";
        document.documentElement.insertBefore(new_react_script,null);
        
        window.setTimeout(
        
            function(){
            
                var email = document.querySelector('#CntctFrm2emailField');
                React.addons.TestUtils.Simulate.change(email, {target: {value: 'testing@gmail.com'}});
            
            },
            3000
        
        );

For example, try to run the above code in this website and you will see it does not work:

http://autoescolalatorreta.wix.com/latorreta#!contact/c24vq

For some reason React is not being exposed with your suggestion of importing dinamycally the React with addon. Probably I am doing something stupid and you are gonna laugh, but I am trying hard and I dont find the right way to make this work.

Again, I thank you your time and effort to clear this out.

**Comment by jurassix** [comment]
Since you have require on the page you can get to react with this:

```javascript
var React = require('react');
```

_However, I this is react v12.2 and I don't see React.addons.TestUtils?_

**Comment by gilperon** [comment]
var React = require('react');

Your code worked perfectly!!! Now I can use the React object inside the console. Indeed my React is 12.2 and I am not using React.addons.TestUtils in this website. How can I load it? I tried the code below but it does not work:

    require('react-test-utils');

I think this is the last thing I need! We are almost there :)

**Comment by jurassix** [comment]
Ah `TestUtils` are only available on un-minified version of React.

You either need to update your require config to use non-minified react or do the following:

```javascript
require.config({
    paths: {
        "react-test": "https://cdnjs.cloudflare.com/ajax/libs/react/0.12.2/react-with-addons"
    }
});
require(['react-test'], function(React) {
  console.log(React);
});
```

**Comment by gilperon** [comment]
Nice, I didnt know that un-minified version of React didnt contain TestUtils. Good point!

So, I change just a little bit your code and pasted it in the console but I still get an error. I opened http://autoescolalatorreta.wix.com/latorreta#!contact/c24vq and in the browser console I pasted this:

        require.config({
        
            paths: {
            
                "react-test": "https://cdnjs.cloudflare.com/ajax/libs/react/0.12.2/react-with-addons"
            }
            
        });
        
        require(['react-test'], function(React) {
        
            var email = document.querySelector('#CntctFrm2emailField');
            React.addons.TestUtils.Simulate.change(email, {target: {value: 'testing@gmail.com'}});
        
        });

And I get this error:

Cannot read property 'Simulate' of undefined

**Comment by jurassix** [comment]
The problem is on your end. I can verify that `React.addons.TestUtils.Simulate` is a valid object in your function scope. If you do in fact have control over this code base you need to ensure you have an `onChange` handler controlling this input.
