### ISSUE TITLE
Is there a way to validate nested objects?

### ISSUE THREAD

**Issue by chodorowicz** [jurassix/react-validation-mixin#25]
I'm using nested object to keep state and https://github.com/EarthlingInteractive/react-deep-link-state to link state. Is there a way to make it work?

**Comment by jurassix** [comment]
The limitation here is with the way I'm flattening the validation errors. Joi handles complex object validation fine. 

I _think_ you can get it to work with the following API's:

```javascript
getValidatorData: function() {
  return {
    username: this.state.user.profile.username,
    password: this.state.user.profile.password
  };
}

validatorTypes: {
  username: Joi.string().alphanum().min(3).max(30).required(),
  password: Joi.string().regex(/[a-zA-Z0-9]{3,30}/)
}
```

_getValidatorData_ is going to flatten your object to be used by this validation library and _validatorTypes_ will just be a simple Joi schema for the resulting flattened data. This should allow you validate the field and get the resulting validations messages from the api.

Give it a try I think this is currently the way to do this. I am working towards a pretty heavy refactor of this lib that will fix this limitation but I'm not sure when those will be ready; weeks/month not days.

**Comment by chodorowicz** [comment]
It's working. Thanks! Will be enough until rewrite is ready. Greets!

**Comment by jurassix** [comment]
I'll try to get validation messages for deep object paths in the next release. It didn't make it in my latest release but should not be to much hard to support now.

[Documentation for 5.0](http://jurassix.gitbooks.io/docs-react-validation-mixin/content/overview/index.html)

**Comment by chodorowicz** [comment]
Cool! :+1:

**Comment by jurassix** [comment]
This has been fixed with 5.2.0: https://github.com/jurassix/react-validation-mixin/releases/tag/v5.2.0

**Comment by jurassix** [comment]
_Ensure you upgrade [joi-validation-strategy to v0.2.0](https://github.com/jurassix/joi-validation-strategy)_

**Comment by chodorowicz** [comment]
Awesome! I will test it out soon!
