### ISSUE TITLE
How to get error types?

### ISSUE THREAD

**Issue by skfd** [jurassix/react-validation-mixin#26]
I want to build username input component.

It must have different tooltips for different validation errors, like "You can't have weird characters in your username", "Username is too short", "username is required" and so on. For example:

    Joi.string().alphanum().min(3).max(30).required()

All I found is `this.state.errors` that contains descriptions of a problem, that I can't customise.
    
    username: ['"Имя" is not allowed to be empty']

Is there a way to get error in more formal way suitable for customisation and localisation?

    username: [required: '"Имя" is not allowed to be empty']

Am I missing something?

**Comment by jurassix** [comment]
There are many issues with Joi on custom validation messages. This on particularly seems to provide what you, and many people, will need; https://github.com/hapijs/joi/issues/546 

Bellow is a typical Joi validation response. In this library we only grab the _path_ and _message_ and push them onto _this.state.errors_. I can easily add the _type_ and a convenience method so you can access it. Then in your code you can build custom messages for this field given specific errors. But it could get verbose for you. 

This change would not take long if you think it would be useful. 

```javascript
[ {
  message: '"zulassung" length must be 5 characters long',
  path: 'zulassung',
  type: 'string.length',
  context: [Object] 
  },  { 
  message: '"name" is required',
  path: 'name',
  type: 'any.required',
  context: [Object] 
}]
```

**Comment by jurassix** [comment]
It seems from the issue above you can try this:

```javascript
email: Joi.string().email().required().language({
  string: {
    email: '!!Aaarrrrrggghhhhh!!! It needs to be valid matey!' // Note the !! escape prefix
  }
})
```

I'm not sure if it's been released yet...so let us know.

**Comment by jurassix** [comment]
This has now been documented. Custom messages is fully supported by Joi.

[Checkout the docs on Custom Messages and I18N](http://jurassix.gitbooks.io/docs-react-validation-mixin/content/overview/custom.html)
