### ISSUE TITLE
How to implement react-validation-mixin with es6 code standard ?

### ISSUE THREAD

**Issue by sijo-vijayan** [jurassix/react-validation-mixin#27]
Hi,
I am a newcomer in ReactJs, I would like to use `react-validation-mixin` in my project. But i don't know how to use it with ES6 standard. Can you update the README.md with ES6. This will be very helpful for people like me. Your help will be highly appreciated.

Thanks
Sijo

**Comment by sebinsua** [comment]
This probably isn't the canonical response, but [this library works for me](https://github.com/brigand/react-mixin).

**Comment by sijo-vijayan** [comment]
@sebinsua Let me try this library. I have one more doubt, Where should I place the code given below in my react component class ? There is any syntax changes ?

  displayName: 'Signup',
  mixins: [ValidationMixin, React.addons.LinkedStateMixin],
  validatorTypes:  {
    firstName: Joi.string().required().label('First Name'),
    lastName: Joi.string().allow(null).label('Last Name'),
    email: Joi.string().email().label('Email Address'),
    username:  Joi.string().alphanum().min(3).max(30).required().label('Username'),
    password: Joi.string().regex(/[a-zA-Z0-9]{3,30}/).label('Password'),
    verifyPassword: Joi.any().valid(Joi.ref('password')).required().label('Password Confirmation')
  },
  getInitialState: function() {
    return {
      firstName: null,
      lastName: null,
      email: null,
      username: null,
      password: null,
      verifyPassword: null,
      feedback: null
    };
  },

**Comment by jurassix** [comment]
@sijo-vijayan - I've been waiting till I hit a next major release to enhance this library for ES6/7 support. I'll see if I can provide a simple top level API that you can use in the interim.

**Comment by sijo-vijayan** [comment]
@jurassix Thank you for you kind reply. :)

**Comment by jurassix** [comment]
ES6 (and ES7) are first class citizens now.

[Documentation for 5.0](http://jurassix.gitbooks.io/docs-react-validation-mixin/content/overview/index.html)
