### ISSUE TITLE
The index of an incorrect array entry is returned instead of the field name

### ISSUE THREAD

**Issue by boldt** [jurassix/react-validation-mixin#39]
As described in the Documentation, you can get the error message for a given field with `this.getValidationMessages('name')`.

If the field is an array, the field name is set to "0", "1", which means that I cannot get the error message for a field with an array.

Small Example: `getValidationMessages()` gives me a result like this: 

```
[
  ""0" must be one of [admin, moderator]",
  ""1" must be one of [admin, moderator]"
]
```

I also reporeted this issue in the Joi project: https://github.com/hapijs/joi/issues/721

Additionally, the error messages doesn't clear, which is already issued in #38.

**Comment by boldt** [comment]
Observtion: The `errors` object returned does look like this:

```
data: Array[0]
data.0: Array[1]
data.1: Array[1]
data.2: Array[1]
```

Thus, `this.getValidationMessages('data')` is emtpy, while `this.getValidationMessages('data.0')`, `this.getValidationMessages('data.1')`, `this.getValidationMessages('data.2')` are set. 

My current workaround: Limit the numer of elemenets and then call:

```
  {this.props.getValidationMessages('data.0').map(this.renderHelpText)}
  {this.props.getValidationMessages('data.1').map(this.renderHelpText)}
  {this.props.getValidationMessages('data.2').map(this.renderHelpText)}
  {this.props.getValidationMessages('data.3').map(this.renderHelpText)}
  {this.props.getValidationMessages('data.4').map(this.renderHelpText)}
  {this.props.getValidationMessages('data.5').map(this.renderHelpText)}
  {this.props.getValidationMessages('data.6').map(this.renderHelpText)}
  {this.props.getValidationMessages('data.7').map(this.renderHelpText)}
  {this.props.getValidationMessages('data.8').map(this.renderHelpText)}
  {this.props.getValidationMessages('data.9').map(this.renderHelpText)}
```

Instead of:

```
  {this.props.getValidationMessages('data').map(this.renderHelpText)}
```

**Comment by jurassix** [comment]
This has been fixed with 5.2.0: https://github.com/jurassix/react-validation-mixin/releases/tag/v5.2.0

**Comment by jurassix** [comment]
_Ensure you upgrade [joi-validation-strategy to v0.2.0](https://github.com/jurassix/joi-validation-strategy)_

**Comment by boldt** [comment]
Looks good as well!
