### ISSUE TITLE
Auto label field keys in validation messages

### ISSUE THREAD

**Issue by ivan-kleshnin** [jurassix/react-validation-mixin#4]
### To recap

Messages like "serialNumber must be a number" are not very friendly. Joi provides an option to override key name in message with label method.

```javascript
validatorTypes: function() {
  return {
    serialNumber: Joi.number().required().label("Serial Number"),
    assemblyDate: Joi.date().required().label("Assembly Date"),
    manufacturer: Joi.string().required().label("Manufacturer),
  };
}
```

But you, probably, have already defined that labels in your form declaration and don't want to repeat it again. To manually handle this it's possible to make validatorTypes a function and access field labels by this.refs.

```javascript
validatorTypes: function() {
  return {
    serialNumber: Joi.number().required().label(this.refs.serialNumber.props.label),
    assemblyDate: Joi.date().required().label(this.refs.assemblyDate.props.label),
    manufacturer: Joi.string().required().label(this.refs.manufacturer.props.label),
  };
},
```

It's a bit more in-sync, but even more verbose :(

---

It's really verbose so my suggestion was to add `autoLabel` propety which could automate this tedious label passing.

```javascript

autoLabel: true // to auto label ALL fields

**OR**

autoLabel: [ // to auto label defined fields
  "serialNumber",
  "assemblyDate"
]
```

The one of possible alternatives I considered is tweaking `validatorTypes` return type:

```javascript
validatorTypes: function() {
  return {
    serialNumber: [Joi.number().required().label(), true], // this is not obvious
    assemblyDate: {validator: Joi.date().required().label(), autoLabel: true}, // this  is too verbose 
    manufacturer: Joi.string().required().label(),
  };
},
```

I like first approach more because it decouples one task from another. `validatorTypes` is already complex enough (accounting it can be map, function... – requires a lot of documentation already).

Name `autoLabel` is probably too generic. Even native React methods are longer (`shouldComponentUpdate`...). So now I think it's better to call it `autoLabelValidations` or even `autoLabelValidationMessages`.

Do you have ideas how this auto-labeling may be implemented differently?

**Comment by jurassix** [comment]
Thanks for breaking this out separately. I hope to have work on this after issue #3 is resolved.

**Comment by jurassix** [comment]
I'm not sure this library is going to support introspection of the user form. I'm closing this issue as there is currently no like functionality in this library. I feel that a consumer of this library can add this abstraction easily and produce a tool/library with these features.
