### ISSUE TITLE
Validate callback called twice?

### ISSUE THREAD

**Issue by idolize** [jurassix/react-validation-mixin#40]
I just updated from `4.x` to `5.x` and code that I had previously been using is now observing odd behavior.

I was previously using code that looked like this:

```js
this.props.validate(error => {
  if (error) {
    return alert('Validation errors');
  }
  sendDataToServer(data);
});
```

...but I noticed that the *callback* to `validate` is being called twice (and thus submitting my data twice) for one call to the `validate` method.

(This was not the behavior for `4.x`)

Right now, I'm using a workaround that looks like this:

```js
let submitting = false;
this.props.validate(error => {
  if (error) {
    return alert('Validation errors');
  }
  if (!submitting) {
    sendDataToServer(data);
  }
  submitting = true;
});
```

but it'd be great to not have to do this :smile:

**Comment by CrisLi** [comment]
+1

**Comment by jurassix** [comment]
What are the versions of the mixin and strategy you're using?

**Comment by jurassix** [comment]
There was a bug in the joi-validation-strategy please upgrade to version 0.1.1 to resolve this issue.

**Comment by idolize** [comment]
@jurassix Thanks for the quick fix! I love the changes in `5.x` btw

**Comment by CrisLi** [comment]
@jurassix It fixed, thanks a lot.
