### ISSUE TITLE
Doesn't work with PureRenderMixin

### ISSUE THREAD

**Issue by idolize** [jurassix/react-validation-mixin#44]
By storing the validation messages an an `Object`, this library unfortunately does not work with a simple `PureRenderMixin` version of `shouldComponentUpdate` (which just does a `===` check over all the `props` and `state`), because even though the `props.errors` object has changed, the reference equality check does not reflect that.

It would be great if the `props.errors` could change reference equality when the errors change (using something like ImmutableJs––[as Facebook suggests](https://facebook.github.io/react/docs/advanced-performance.html#immutable-js-to-the-rescue)––or even just by using the ES6 spread operator (ex: `this.setState({ errors: { ...nextErrors } })` instead of `this.setState({ errors: nextErrors })`

**Comment by jurassix** [comment]
fixed and published in v5.2.1

**Comment by idolize** [comment]
Awesome thanks :+1:
