### ISSUE TITLE
getValidationMessages error for object validation

### ISSUE THREAD

**Issue by boldt** [jurassix/react-validation-mixin#47]
Imagine the following Joi:

```
{
  thumbnail : {
    height : Joi.number().required()
  }
}
```

Calling `getValidationMessages('thumbnail')` returns me the following error: `Uncaught TypeError: html.replace is not a function`

Stacktrace:
```
decode	@	he.js:221
decode	@	decode.js:26
getValidationMessages	@	validationFactory.js:37
getValidationMessages	@	validationMixin.js:65
```

The issue is simple: `decode.js` does not check for objects. Thus, `replace` is called on an object instead of a string.

**Comment by jurassix** [comment]
I put together a test for this. It looks like all you need to do is the following:

```js
getValidationMessages('thumbnail.height')
```

**Comment by jurassix** [comment]
Technically `thumbnail` is just an object but `height` is the Joi schema.

**Comment by jurassix** [comment]
This should work the same way as asking if this field is valid or to validate the field:

```js
this.props.isValid('thumbnail.height')
this.props. handleValidation'(thumbnail.height')
this.props.getValidationMessages('thumbnail.height')
```
