### ISSUE TITLE
IE8 compatibility: some js reserved words used in both joi and some browserify shims

### ISSUE THREAD

**Issue by yicone** [jurassix/react-validation-mixin#48]
- IE8 can't accept some js reserved words as property, but `joi` uses some of these  
 e.g `internals.Alternatives.prototype.try`, `internals.Any.prototype.default`
- `joi` run on browser need supported by some `browserify` shims, but these also contains some js reserved words that IE8 can't accept

If these problems do exist, does that mean, `react-validation-mixin` is not compatible with IE8?

**Comment by jurassix** [comment]
Right now this library makes no guarantees about browser support. I would expect at a minimum the usage of Shim, Shams, Shivs for compatibility when testing in IE8. If you would like to update reserved words within this library please submit a PR and we can work together to resolve those.

**Comment by yicone** [comment]
Because these reserved words not in this library but `joi` and `browserify`, so I can't resolve these issues by make a PR. 
And there was another issue about `joi`, it need very much of shims codes provided by `browserify`, for mapping Nodejs object to browser, that lead to larger `bundle` loaded in browser.

I means, may be `joi` not  a good choice(partner) for `react-validation-mixin`.

(For my current project, in order to avoid these issues, I write a simple `validation strategy` just for my project. Thanks you for the design that allow of custom `validation strategy`)

**Comment by jurassix** [comment]
I believe Browserify should be fine for IE8 - we use this in production for over a year. Joi may be different.
