### ISSUE TITLE
Custom error message

### ISSUE THREAD

**Issue by agile116** [jurassix/react-validation-mixin#49]
Hi,

I have the following two dates fields defined in validatorTypes. I'd like to show error message like "START DATE must be earlier than END DATE." Is it possible and how? Thanks.
startDate: Joi.date().max(Joi.ref('endDate')).required().label('START DATE'),
endDate:Joi.date().required().label('END DATE'),

**Comment by xicombd** [comment]
Yes, checkout this page: https://jurassix.gitbooks.io/docs-react-validation-mixin/content/overview/custom.html

You could pass something like this as a language to `startDate `: 
```javascript
{
  date: {
    max: 'must be earlier than END DATE'
  }
}
```

**Comment by agile116** [comment]
Thanks：）


杨小林

**Comment by jurassix** [comment]
@agile116 let us know if you need any additional help.

**Comment by agile116** [comment]
Is it working now. Thanks

杨小林
