### ISSUE TITLE
Joi is a requirement or an option

### ISSUE THREAD

**Issue by ivan-kleshnin** [jurassix/react-validation-mixin#5]
To continue discussion in https://github.com/jurassix/react-validation-mixin/issues/3

If Joi is optional – documentation needs to be updated and clarified a bit.
I can help with this. Please approve.

**Comment by jurassix** [comment]
Approved. Thanks again.

**Comment by ivan-kleshnin** [comment]
https://github.com/jurassix/react-validation-mixin/pull/7
