### ISSUE TITLE
Validation property preprocessing

### ISSUE THREAD

**Issue by Volodymyr128** [jurassix/react-validation-mixin#50]
Sounds like an anti-pattern, but I don't see another way. I have lots of fields which may contain space characters (i.e. e-mail field). I validate e-mail with `Joi.string().email().min(5).max(50).required()`, but I want the next e-mail be valid `"       some-email@gmail.com            "`, and just trim when send to the server

**Comment by jurassix** [comment]
Do your pre-processing in the `getValidatorData` API. You can easily preprocess your form data here before validation.

**Comment by Volodymyr128** [comment]
Thank you !!!!!
