### ISSUE TITLE
Change the name from mixin to higher order component, or Decorator

### ISSUE THREAD

**Issue by franleplant** [jurassix/react-validation-mixin#53]
Hi!
    First of all thanks for this library, I like it much better than the other alternatives out there (not that there are particularly a lot of them).

I dont think that `mixin` being part of the name is accurate, this lib behaves like a [higher order component](https://gist.github.com/sebmarkbage/ef0bf1f338a7182b6775) and you could even say like a decorator.
So, the main idea is to propose a name change!

Thanks!
Fran

**Comment by jurassix** [comment]
As of 5.x of this library is implemented as a Higher Order Component (HoC.) Prior to 5.x the library implementation was the standard `React.createClass` mixin. 

I can easily change the GitHub name to reflect the implementation changes; but what about npm registry?

__Any suggestions from the community about repo naming and impacts of an npm package name changes would be appreciated__

**Comment by franleplant** [comment]
Changing the repo's name isnt a problem but the npm's name it might. This might be the _mainstream_ solution: http://stackoverflow.com/questions/28371669/renaming-a-published-npm-module

**Comment by jurassix** [comment]
My plan for this is to move this library out of my personal repository lists and into a community owned repo. I'll make try to incorporate these suggestions into that move. No ETA on this yet but is part of the game plan. Need to move out of person control and into community space.
