### ISSUE TITLE
Can you please provide the source code for the live demo?

### ISSUE THREAD

**Issue by stenio123** [jurassix/react-validation-mixin#54]
Docs at https://jurassix.gitbooks.io/docs-react-validation-mixin/content/overview/index.html are great, but I am struggling to implement the "Basic Examples". If I could just see the code on the demo it would bring a world of clarity!

**Comment by jurassix** [comment]
Here you go: https://github.com/jurassix/react-validation-mixin/blob/master/spec/components/Signup.js

**Comment by jurassix** [comment]
The above does need to be updated to ES6, but it is the Component that is used for the demo. You can check that all out on the [gh-pages branch of this library](https://github.com/jurassix/react-validation-mixin/tree/gh-pages).
