### ISSUE TITLE
Firefox throws "SyntaxError: let is a reserved identifier"

### ISSUE THREAD

**Issue by dineshi2it** [jurassix/react-validation-mixin#55]
react-validation-mixin works fine in chrome but not in firefox. A quick googling resulted in using "babel" to convert ES6 to ES5. I'm new to node framework. Can anyone help me to fix this?

**Comment by jurassix** [comment]
I'll take a look.

**Comment by dineshi2it** [comment]
But this demo(http://jurassix.github.io/react-validation-mixin/) works well in firefox. It would be great if I get the source code of that.

**Comment by jurassix** [comment]
Code for the demo is hidden in plain sight ;) #54

**Comment by jurassix** [comment]
I searched the __lib/__ folder that is packaged with this library on `npm i react-validation-mixin` and find no references to `lib`. 

It seems more likely that your also using ES6 and have introduced __let__ keyword? Check your `babel` config?

**Comment by jurassix** [comment]
Ok I re-read your initial post. You need to use __babel__ to transpile your source code into ES5.

Checkout the following from this library to get up and running quick:

[.babelrc](https://github.com/jurassix/react-validation-mixin/blob/master/.babelrc) _sets babel options_
[package.json](https://github.com/jurassix/react-validation-mixin/blob/master/package.json) _look at the __build:lib__ target and the __babel-*__ deps_

And that should do it. In this library the __src/__ folder is ES2015 and is transpiled to the __lib/__ and packed for node. When you install from node you only pull down the __lib/__ folder and have an ES5 module that should work in modern browsers.

Good luck.
