### ISSUE TITLE
Inconsistent getValidationMessages()

### ISSUE THREAD

**Issue by boldt** [jurassix/react-validation-mixin#56]
* if `getValidationMessages('field')` is valid, I am getting an empty array: `[]`
* if `getValidationMessages('field')` returns a singe message, I am getting a string: `"E-Mail" must be a valid email`

The data type returned by getValidationMessages should stay the same, e.g. `array`. Means: even if I get just a singe message, it should be an array: `['"E-Mail" must be a valid email']`

**Comment by jurassix** [comment]
Yeah this was supposed to be fixed with the [last release](https://github.com/jurassix/react-validation-mixin/releases/tag/v5.3.1)
Can you upgrade and let me know?

**Comment by boldt** [comment]
Works as expected with the last upgrade. Thanks!

**Comment by jurassix** [comment]
Thanks for the report!
