### ISSUE TITLE
Decoding via "he" fails when errors are nested (expects String - gets an Object)

### ISSUE THREAD

**Issue by idolize** [jurassix/react-validation-mixin#59]
I've noticed that react-validation-mixin contains code to decode error messages using the following branching paths:

```js
export default function decode(list, key) {
  if (defined(list, key)) {
    const value = get(list, key);
    if (Array.isArray(value)) {
      return value.map(he.decode);
    }
    return value ? he.decode(value) : '';
  }
}
```

However, when I run `getValidationMessages()` in my project it blows up here, because `value` is coming back as an `Object` keyed with `Arrays` for each invalid field. Thus, when `decode` runs it tries to run `he.decode` on an `Object` (which expects a `String` and thus can't find the `String.replace` method and throws an `Exception`).

![screen shot 2015-11-12 at 12 12 59 pm](https://cloud.githubusercontent.com/assets/635005/11129988/6fdd1cb2-8937-11e5-8962-f57636bfe067.png)

I'm using react-validation-mixin version 5.3.1.

**Comment by idolize** [comment]
It appears `get(list, key)` is returning another `Object` mapped by key.

Maybe instead of:
```js
export default function decode(list, key) {
  if (defined(list, key)) {
    const value = get(list, key);
    if (Array.isArray(value)) {
      return value.map(he.decode);
    }
    return value ? he.decode(value) : '';
  }
}
```

it should be recursive? Something like:
```js
export default function decode(list, key) {
  if (defined(list, key)) {
    const value = get(list, key);
    if (isPlainObject(value)) { // isPlainObject from lodash
      return Object.keys(value).map(decode.bind(this, value));
    }
    if (Array.isArray(value)) {
      return value.map(he.decode);
    }
    return value ? he.decode(value) : '';
  }
}
```

Or depending on the depth, if this pattern is consistent, then you could avoid recursion like:
```js
export default function decode(list, key) {
  if (defined(list, key)) {
    const value = get(list, key);
    return Object.keys(value).map(subDecode.bind(this, value));
  }
}

function subDecode(list, key) {
  const value = get(list, key);
  if (Array.isArray(value)) {
    return value.map(he.decode);
  }
  return value ? he.decode(value) : '';
}
```

**Comment by idolize** [comment]
(I updated the title because it seems like it only happens on validation errors that come from within nested objects)

**Comment by jurassix** [comment]
Thanks for the report. I'll try to get some tests around this.

**Comment by idolize** [comment]
Thanks @jurassix

**Comment by jurassix** [comment]
I'm thinking the easiest place to handle this is [inside the Joi strategy and not a top level concern of this library](https://github.com/jurassix/joi-validation-strategy/blob/master/src/joiValidationStrategy.js#L19). Also, the Joi validation results are returned flat, mapping over them and applying decode is simpler. 

However, I have one issue now. `getValidationMessages` needs to return an array of error messages, [in order to achieve this I have to flatten a complex object](https://github.com/jurassix/react-validation-mixin/blob/master/src/validationFactory.js#L11). Looking for a good solution for this.

**Comment by idolize** [comment]
If the Joi strategy is updated to return objects keyed by the "invalid property name" with the values being the error strings, wouldn't something like `Object.keys(errors).map(key => errors[key])` suffice?

**Comment by jurassix** [comment]
We support nested schema's so objects can have a structure like: 
```js
{a: {b: {c: "is required"}}}
```

**Comment by jurassix** [comment]
```js
function flattenErrorsObject(obj) {
  var values = [];
  if(_.isObject(obj)) {
    values = _.values(obj);
  }  else if(_.isString(obj)) {
    return obj;
  }
  var flat = values.map(value => {
    if (!_.isString(value)) {
      return flattenErrorsObject(value);
    }
    return value;
  });  
  return _.flatten(flat);
}
```

```js
var test = {a:'me', b: {c: 'c', d: {e:['f','g']}}};
```

```js
> flattenErrorsObject(test)
< ["me", "c", "f", "g"]
```

**Comment by jurassix** [comment]
Think you can code review this? Is there a better way to do this?

**Comment by jurassix** [comment]
@idolize I refactored the above algorithm [here](https://github.com/jurassix/react-validation-mixin/blob/master/src/utils/flattenErrorsObject.js)

This issue should be fixed with the following patches:

react-validation-mixin v5.3.2
joi-validation-strategy v0.3.2
