### ISSUE TITLE
Add reference to react-validatorjs-strategy

### ISSUE THREAD

**Issue by TheChech** [jurassix/react-validation-mixin#67]
https://github.com/TheChech/react-validatorjs-strategy

Uses the [validatorjs](https://github.com/skaterdav85/validatorjs) library, which is a lot leaner than Joi.

**Comment by jurassix** [comment]
Great work! I'll update the docs and readme to reflect this contribution.

**Comment by jurassix** [comment]
Updated README and added it to the install page in the docs. https://jurassix.gitbooks.io/docs-react-validation-mixin/content/overview/install.html

NPM landing page will not be updated until the next patch/release.

Thanks again for your library.

**Comment by TheChech** [comment]
Thanks, although you've accidentally linked react-validatorjs-strategy to the validatorjs page.

**Comment by jurassix** [comment]
yeah - seems like this was fixed in another PR though. Apologies. I'll update the docs also to point to the correct repo.
