### ISSUE TITLE
Regex and password text being displayed in error message

### ISSUE THREAD

**Issue by KishoreBarik** [jurassix/react-validation-mixin#69]
When we provide regex in strategy, the library displays the regex in error message. We can't imagine our users will be able to understand the regex nor they need to.
From the demo page itself I got this message
**"Password" with value "gh" fails to match the required pattern: /[a-zA-Z0-9]{3,30}/**
Also I feel we should not be displaying the entered password in error message.

**Comment by jurassix** [comment]
Take a look at the documentation on customized messages: [https://jurassix.gitbooks.io/docs-react-validation-mixin/content/overview/custom.html](https://jurassix.gitbooks.io/docs-react-validation-mixin/content/overview/custom.html)
