### ISSUE TITLE
React.findDOMNode instead of findDOMNode

### ISSUE THREAD

**Issue by jamesryan-dev** [jurassix/react-validation-mixin#81]
cc: http://stackoverflow.com/questions/29336178/react-finddomnode-comes-as-undefined

Was hitting an error in my react.app when using this but by adding `React.findDOMNode` instead of `findDOMNode` within the `getValidatorData()` function I could carry on working.. 

Don't know if this is a prevalent issue but thought I'd recommend a change to Docs re this.. 

/shrug 

jimmy

**Comment by jamesryan-dev** [comment]
Realise now cause my import was different 
prob not a reason to raise an issue eh 😅

**Comment by jurassix** [comment]
Yeah this library is in need of some TLC. Was started awhile ago. Thanks for the issue. I'll try to put some time in to get this current.
